Bot, FileText, ListChecks, Notebook, PenTool, Languages,
    ImageMinus, Scaling, Wand2, Palette, Minimize2, FileType2,
    Combine, RotateCw, Upload, Sun, Moon, File, Loader2, ArrowRight, Download, Check, X,
    CheckCircle, FileSymlink, Image, Images, Lock, Zap, CreditCard, Copy, Sparkles,
    Eraser, Scissors, ArrowRightLeft, Smartphone, Table, Video, UserCircle

export const Icons = {
    Bot,
    FileText,
    ListChecks,
    Notebook,
    PenTool,
    Languages,
    Download,
    ImageMinus,
    Scaling,
    Wand2,
    Palette,
    Minimize2,
    FileType2,
    Combine,
    RotateCw,
    Upload,
    Sun,
    Moon,
    File,
    Loader2,
    ArrowRight,
    Check,
    X,
    CheckCircle,
    FileSymlink,
    Image,
    Images,
    Lock,
    Zap,
    CreditCard,
    Copy,
    Sparkles,
    Eraser,
    Scissors,
    ArrowRightLeft,
    Smartphone,
    Table,
    Video,
    UserCircle,
    // Aliases for legacy support if needed
    Compress: Minimize2,
    PdfToWord: FileType2,
    RemoveBg: ImageMinus,
    Merge: Combine
};
