import jsPDF from 'jspdf';

interface NotesData {
    title?: string;
    topics?: { heading: string; points: string[] }[];
}

/**
 * Generate a beautifully formatted PDF from AI Notes
 */
export function downloadNotesAsPdf(data: NotesData, filename: string) {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let y = 25;

    const checkPageBreak = (needed: number) => {
        if (y + needed > doc.internal.pageSize.getHeight() - 20) {
            doc.addPage();
            y = 20;
        }
    };

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(30, 41, 59); // slate-800
    const titleLines = doc.splitTextToSize(data.title || 'Notes', contentWidth);
    doc.text(titleLines, margin, y);
    y += titleLines.length * 10 + 5;

    // Divider
    doc.setDrawColor(148, 163, 184); // slate-400
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    // Subtitle
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Generated by FileSwift AI • ${new Date().toLocaleDateString()}`, margin, y);
    y += 12;

    // Topics
    (data.topics || []).forEach((topic, idx) => {
        checkPageBreak(25);

        // Topic heading
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(13);
        doc.setTextColor(37, 99, 235); // blue-600
        const headingText = `${idx + 1}. ${topic.heading}`;
        const headingLines = doc.splitTextToSize(headingText, contentWidth);
        doc.text(headingLines, margin, y);
        y += headingLines.length * 6 + 4;

        // Points
        (topic.points || []).forEach((point) => {
            checkPageBreak(12);
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            doc.setTextColor(51, 65, 85); // slate-700

            const bulletX = margin + 4;
            const textX = margin + 10;
            const pointLines = doc.splitTextToSize(point, contentWidth - 12);

            doc.setTextColor(37, 99, 235);
            doc.text('•', bulletX, y);
            doc.setTextColor(51, 65, 85);
            doc.text(pointLines, textX, y);
            y += pointLines.length * 5 + 3;
        });

        y += 6; // spacing between topics
    });

    // Footer on last page
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by FileSwift — fileswift.in', margin, pageHeight - 10);

    doc.save(filename);
}

/**
 * Generate a PDF from rewritten or translated text
 */
export function downloadTextAsPdf(text: string, filename: string, label: string) {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let y = 25;

    // Title/Label
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(30, 41, 59);
    doc.text(label, margin, y);
    y += 12;

    // Subtitle
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by FileSwift AI • ${new Date().toLocaleDateString()}`, margin, y);
    y += 10;

    // Divider
    doc.setDrawColor(148, 163, 184);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    // Body text
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(51, 65, 85);

    const lines = doc.splitTextToSize(text || '', contentWidth);
    const lineHeight = 5.5;

    lines.forEach((line: string) => {
        if (y + lineHeight > doc.internal.pageSize.getHeight() - 20) {
            doc.addPage();
            y = 20;
        }
        doc.text(line, margin, y);
        y += lineHeight;
    });

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by FileSwift — fileswift.in', margin, pageHeight - 10);

    doc.save(filename);
}
